<%@ page import="mypack.DatabaseUtil"%>
<%@ page import="java.sql.*"%>
<%
String submittedOtp = request.getParameter("otp");
String sessionOtp = (String) session.getAttribute("signup_otp");

if (submittedOtp == null || sessionOtp == null) {
	response.sendRedirect("signUp.jsp");
	return;
}

if (submittedOtp.equals(sessionOtp)) {
	// OTP verified! Retrieve user details from session
	String name = (String) session.getAttribute("signup_username");
	String password = (String) session.getAttribute("signup_password");
	String email = (String) session.getAttribute("signup_email");
	String first = (String) session.getAttribute("signup_firstName");
	String last = (String) session.getAttribute("signup_lastName");
	String mobile = (String) session.getAttribute("signup_phone");
	String address = (String) session.getAttribute("signup_address");
	String dob = (String) session.getAttribute("signup_dob");
	String type = (String) session.getAttribute("signup_usertype");

	if (name == null || password == null || email == null) {
		response.sendRedirect("signUp.jsp");
		return;
	}

	String hashedPassword = DatabaseUtil.hashPassword(password);

	Connection con = null;
	PreparedStatement ps = null;

	try {
		con = DatabaseUtil.getCon();
		
		// Insert user (user_id is auto-generated by sequence SET DEFAULT nextval)
		String sql = "INSERT INTO users (username, password, email, firstName, lastName, phone, address, dob, usertype) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
		ps = con.prepareStatement(sql);
		ps.setString(1, name);
		ps.setString(2, hashedPassword);
		ps.setString(3, email);
		ps.setString(4, first);
		ps.setString(5, last);
		ps.setString(6, mobile);
		ps.setString(7, address);
		ps.setDate(8, java.sql.Date.valueOf(dob));
		ps.setString(9, type);

		int rowsAffected = ps.executeUpdate();
		
		// Clear session parameters
		session.removeAttribute("signup_username");
		session.removeAttribute("signup_password");
		session.removeAttribute("signup_email");
		session.removeAttribute("signup_firstName");
		session.removeAttribute("signup_lastName");
		session.removeAttribute("signup_phone");
		session.removeAttribute("signup_address");
		session.removeAttribute("signup_dob");
		session.removeAttribute("signup_usertype");
		session.removeAttribute("signup_otp");

		if (rowsAffected > 0) {
			response.sendRedirect("login.jsp?msg=Valid");
		} else {
			response.sendRedirect("index.jsp?msg=Invalid");
		}

	} catch (Exception e) {
		e.printStackTrace();
		response.sendRedirect("index.jsp?msg=Error&error=" + e.getMessage());
	} finally {
		try {
			if (rs != null) rs.close();
			if (stmtSelect != null) stmtSelect.close();
			if (ps != null) ps.close();
			if (con != null) con.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
} else {
	// OTP code mismatch. Redirect back and retain demo OTP if active.
	response.sendRedirect("verifyOTP.jsp?msg=invalidOtp&otp=" + sessionOtp);
}
%>
